### ISSUE TITLE
Implement BaseVisualCamelEntity for Kamelet CRD

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#110]
### Context
Currently, there's only support to render Camel Routes in the `Design` section of kaoto-next.

### Goal
This issue aims to implement a `BaseVisualCamelEntity` for the `Kamelet` CRD.

### Requisites
- [X] Support a VisualEntity flow, meaning the user can interact with nodes by adding, removing,  replacing, or configuring them. https://github.com/KaotoIO/kaoto-next/pull/421

- [X] Support the dependencies array.
    a. Delegated into https://github.com/KaotoIO/kaoto-next/issues/489, as it's not a priority at the moment.

- [X] Support for Metadata configuration like annotations, labels, and the icon.
    a. https://github.com/KaotoIO/kaoto-next/pull/480

- [X] Handle special Kamelets boundaries. (`kamelet:source` & `kamelet:sink`):
    a. https://github.com/KaotoIO/kaoto-next/pull/429
    b. https://github.com/KaotoIO/kaoto-next/pull/445
    c. https://github.com/KaotoIO/kaoto-next/pull/455

### Notes
* [Camel Route Example](https://github.com/KaotoIO/kaoto-next/blob/c633b07c419fad48f0e4b65b3f4a0687819aa4ba/packages/ui/src/models/camel-entities/flows/route.ts)

* After building `kaoto-next/packages/camel-catalog`, using `yarn workspace @kaoto-next/camel-catalog run build`, you will find the `Kamelet` CRD JSON Schema in `packages/camel-catalog/dist/crd-schema-kamelets-2.1.0-SNAPSHOT.json`

* You could use a Typescript definition for `Kamelet` like:
```typescript
import { Kamelet } from '@kaoto-next/camel-catalog/types';
```

**Comment by lordrip** [comment]
@mmelko I'm assigning it to you since we talked about that you might have the bandwidth to take it, that being said, feel free to unassign it if that's not accurate :smiley:

**Comment by lhein** [comment]
undoing the assignment. please only assign issues when you start working on it.
