### ISSUE TITLE
Implement BaseVisualCamelEntity for KameletBinding CRD

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#111]
### Context
Currently, there's only support to render Camel Routes in the `Design` section of kaoto-next.

### Goal
This issue aims to implement a `BaseVisualCamelEntity` for the `KameletBinding` CRD.

### Notes
* [Camel Route Example](https://github.com/KaotoIO/kaoto-next/blob/c633b07c419fad48f0e4b65b3f4a0687819aa4ba/packages/ui/src/models/camel-entities/flows/route.ts)

* After building `kaoto-next/packages/camel-catalog`, using `yarn workspace @kaoto-next/camel-catalog run build`, you will find the `Kamelet` CRD JSON Schema in `packages/camel-catalog/dist/crd-schema-kameletbindings-2.1.0-SNAPSHOT.json`

* You could use a Typescript definition for `KameletBinding` like:
```typescript
import { KameletBinding } from '@kaoto-next/camel-catalog/types';
```

**Comment by tplevko** [comment]
Already done in https://github.com/KaotoIO/kaoto-next/pull/122
