### ISSUE TITLE
Implement BaseVisualCamelEntity for Pipe CRD

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#112]
### Context
Currently, there's only support to render Camel Routes in the `Design` section of kaoto-next.

### Goal
This issue aims to implement a `BaseVisualCamelEntity` for the `Pipe` CRD.

### Notes
* [Camel Route Example](https://github.com/KaotoIO/kaoto-next/blob/c633b07c419fad48f0e4b65b3f4a0687819aa4ba/packages/ui/src/models/camel-entities/flows/route.ts)

* After building `kaoto-next/packages/camel-catalog`, using `yarn workspace @kaoto-next/camel-catalog run build`, you will find the `Pipe` CRD JSON Schema in `packages/camel-catalog/dist/crd-schema-pipes-2.1.0-SNAPSHOT.json`

* You could use a Typescript definition for `Kamelet` like:
```typescript
import { Pipe } from '@kaoto-next/camel-catalog/types';
```

**Comment by lordrip** [comment]
Closed with https://github.com/KaotoIO/kaoto-next/pull/140

**Comment by lhein** [comment]
done
