### ISSUE TITLE
Provide a better mechanism to refresh the Canvas component

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#119]
### Describe the Bug

When opening the `Design` pane in `kaoto-next`, there's a flash in the `Canvas` component.

### Steps to Reproduce the Bug or Issue

1. Go to the `Design` pane
2. Notice the flash when loading the `Canvas` component for the first time

### Screenshots or Videos

[Screencast from 2023-09-12 12-46-37.webm](https://github.com/KaotoIO/kaoto-next/assets/16512618/2b97ca4b-f390-4b6b-8b67-12bd8b8d8fbc)

### Platform

- OS: [Linux]
- Browser: [Firefox]

**Comment by tplevko** [comment]
Fixed in https://github.com/KaotoIO/kaoto-next/pull/130
