### ISSUE TITLE
Catalog view - store layout selection

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#184]
### Please describe the feature that you want to propose

It would be good for the user experience to store the List/Gallery view state globally.

![Peek 2023-10-04 07-38](https://github.com/KaotoIO/kaoto-next/assets/4180208/ea39e594-3e4d-40d6-b7b6-99aebade42bf)

**Comment by lordrip** [comment]
@tplevko This can be done using the `useLocalStorage` hook.

There's [an example here](https://github.com/KaotoIO/kaoto-next/blob/f6c53c8d8fad4eff8df847b1a79e4401b575890e/packages/ui/src/layout/Shell.tsx#L15-L16)
