### ISSUE TITLE
Show component details in the Catalog

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#21]
### Please describe the feature that you want to propose

Currently, by clicking on a component tile, the component name gets printed in the console.
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/e1a6173a-8bb2-40f2-8aaf-3c63789c95e4)

### Goal
The idea for this feature would be to show a `Modal` view with more detailed information about the component, like its entire description and a list of the properties and their description.

This modal should be part of the `components` folder but be connected to the `CatalogPage` component. The idea here is to be able to use the same catalog without this functionality in the future as well.

### Related links
* [Modal component](https://www.patternfly.org/components/modal)
* [Table component](https://www.patternfly.org/components/table)

**Comment by lhein** [comment]
Nice, that looks good!

**Comment by lordrip** [comment]
Indeed, that seems very cool @mkralik3, feel free to send a pull request with your changes :smiley:

**Comment by mkralik3** [comment]
@lordrip  Sure, I have to do some refactor before :)
