### ISSUE TITLE
Remove node in Pipe/KB doesn't work

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#253]
### Describe the Bug

When users try to remove nodes from KB/Pipe, it doesn't get removed.

### Steps to Reproduce the Bug or Issue

1. create KB/Pipe
2. try to remove nodes
3. see the node wasn't removed

### Screenshots or Videos

![Peek 2023-10-25 10-00](https://github.com/KaotoIO/kaoto-next/assets/4180208/e2697231-8072-4794-8df5-d322d78f3379)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lordrip** [comment]
Fixed as part of https://github.com/KaotoIO/kaoto-next/pull/267
