### ISSUE TITLE
Canvas component is blinking when configuring nodes

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#266]
### Describe the Bug

When writing properties in the side panel, the canvas component has a flickering.

### Steps to Reproduce the Bug or Issue

1. Open a camel route
2. Configure a node
3. Notice how the graph gets moved and then gets relocated again.

### Screenshots or Videos

[Screencast from 2023-10-31 14-05-34.webm](https://github.com/KaotoIO/kaoto-next/assets/16512618/30fbc8c4-05db-4873-9260-199b92b27001)

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [0.2.0]

**Comment by lhein** [comment]
Is that related to or duplicating  #213 ?

**Comment by lhein** [comment]
@lordrip ?

**Comment by lordrip** [comment]
Sorry, I missed the notification, it's related to #213, but not the same root cause.
