### ISSUE TITLE
Support for URI field

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#274]
### Please describe the feature that you want to propose

Currently, there's no handling for the `URI` field in the configuration form.

The goal would be to have this field updated with the parameters specified in the configuration form.

### Goals:
1. Hide the URI field from the Config Form
2. For path parameters like `[loggerName](https://github.com/apache/camel/blob/camel-4.2.x/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/log.json#L31)`, the field should be present in the Config Form, but it shouldn't be as a defined property, it should go instead to the appropriate path section of the syntax
3. For query parameters in the URI, those should be populated as parameters and removed from the URI field

### Prerequisites
* https://github.com/KaotoIO/kaoto-next/issues/296

**Comment by lhein** [comment]
and also the other way round. If a user enters the uri, then the corresponding form fields need to be updated. Alternatively we can think about making the URI a readonly value or hiding it fully (we need to ensure that we can configure everything in the form fields before doing this)

**Comment by apupier** [comment]
note that when creating a "new route", the uri field with path parameter is used. if we fill the value from property panel ,this value is ignored at runtime.

**Comment by lordrip** [comment]
> note that when creating a "new route", the uri field with path parameter is used. if we fill the value from property panel ,this value is ignored at runtime.

This is very good information @apupier, thanks for bringing this up, maybe we could signal this on the UI side as well, so the user could know it also and avoid the surprise.

**Comment by lhein** [comment]
The more I think about it my conclusion is that we should not stick to the discouraged way of configuring nodes via URI parameters. Instead we should stick to the new preferred way and specify them as parameters. That means we take whatever the user enters / pastes as uri but then remove everything and place it in the parameters section instead.
