### ISSUE TITLE
Respect consumerOnly and producerOnly settings in the catalog

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#276]
### Please describe the feature that you want to propose

In the Camel catalog we have information about components being only consumers, only producers or both. This is defined via 2 config values called `producerOnly` and `consumerOnly`.

![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/6f2c8ee7-7bc3-45ea-8409-7bcd7da1fbb4)

We need to improve the validation and the filtering in the Kaoto catalog to only suggest valid components in the right positions.

**Comment by lordrip** [comment]
Implemented in #288 here https://github.com/KaotoIO/kaoto-next/commit/bd38797e64403feb2ac0005c9997a5fdad3eede6
