### ISSUE TITLE
Show helping descriptions for parameters in the config panel

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#281]
### Please describe the feature that you want to propose

The camel catalog provides helping information about all the configurable properties via the `description` attribute. 
We should leverage these texts and show it in some way for the parameters. I could imagine to have an info or question symbol next to the parameter and if you hover over it and/or the field itself we could display a tool tip.

**Comment by lordrip** [comment]
This is how was done in v1: https://github.com/KaotoIO/kaoto-ui/blob/main/packages/kaoto-ui/src/components/CustomJsonSchemaBridge.tsx
