### ISSUE TITLE
Mark required configuration parameters as mandatory in the right side panel

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#282]
### Please describe the feature that you want to propose

The camel catalog provides information about parameters being optional or mandatory via the attribute `required`. We should indicate mandatory parameters (`"required": true`) in the configuration panel and as a second iteration if these fields are not filled they should be marked as in error. (either via a status icon on the input field or by using other means like a red background color in the input field, which might be not ideal in terms of accessibility)

**Comment by lhein** [comment]
This is currently not fully working. While the URI field for endpoints is marked as required, other parameters like the name for a direct endpoint are not. 



![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/5983a7ca-21dc-4d7d-b8d0-ba239d736546)

**Comment by lhein** [comment]
Moving this bug to the feature parity milestone because we had that working in Kaoto v1.

**Comment by apupier** [comment]
The `definition` and `compiledSchema` are not containing the `required` parameter (`timerName` is required, see https://camel.apache.org/components/4.0.x/timer-component.html#_path_parameters_1_parameters) :

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/9cfef87b-6cbe-439d-8610-0f384c3927f5)

The json catalog in dist folder has the correct `required` attribute:
![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/cdc37517-9a9e-4bee-9639-6e35dc03ce8c)

**Comment by apupier** [comment]
if it is required based on the provided schema/definition is done here

https://github.com/KaotoIO/kaoto-next/blob/d7c317336ed54811686dcb27d61924ae36ccaddf/packages/ui/src/components/Form/JSONSchemaBridge.ts#L178-L180

**Comment by apupier** [comment]
moved to other topics.

A solution consist in adding ```required: componentSchema.required,``` to camel-component-schema.service.ts line 219.

I didn't had time to start looking how to provide a test
