### ISSUE TITLE
Mark deprecated configuration options

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#284]
### Please describe the feature that you want to propose

The camel catalog provides information on deprecated configuration properties via the attributes `deprecated` and `deprecationNote`.

We should place an indicator next to deprecated config fields (`deprecated: true`) and on hovering we then show a tool tip with the content of `deprecationNote` if provided.

The information is already present in the JSON Schema, we just need to implement this feature in the [`uniforms-patternfly`](https://github.com/KaotoIO/uniforms-patternfly) library

**Comment by lordrip** [comment]
The goal would be to have a warning icon alongside the information icon, that shows a `Deprecated` word. Ideally, we should be able to see the deprecationNote, but I haven't seen them in the catalog.

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/acacc81d-96fc-44c7-b012-fbf505d61b28)
