### ISSUE TITLE
Check if we mark deprecations in the Kaoto Catalog

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#287]
### Please describe the task that needs to be done

The Camel catalog provides deprecation information for components in general but also for all the configuration options for that component. We need to check and ensure that we mark deprecated components as well as configuration options in the Kaoto catalog so users can easily spot this information. Also incorporate a deprecation explanation if given. 

See camel catalog attributes: 
`deprecated`
`deprecationNote`

**Comment by lhein** [comment]
Deprecated components should have a visible "Deprecated" tag in the tile analog to "Stable" and "Preview".

**Comment by lordrip** [comment]
First iteration of marking a component as deprecated: https://github.com/KaotoIO/kaoto-next/pull/288
