### ISSUE TITLE
Copy to clipboard functionality

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#295]
### Please describe the feature that you want to propose

As a User, I would like to have the possibility to copy the underlying Source Code into the clipboard.

It would be beneficial to have a dedicated button in the Visualization toolbar:
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/289e02cf-1e45-49b4-bb66-799e33759060)

Note: This functionality is already provided in the Source Code editor as part of @patternfly

### Related browser API
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API

### Related @patternfly API
https://www.patternfly.org/components/clipboard-copy#clipboardcopy

**Comment by corners2wall** [comment]
@lordrip, assign to me please. I already in process

**Comment by lhein** [comment]
done, Have fun and thanks for your help! :)

**Comment by corners2wall** [comment]
@lhein , @lordrip  could anybody review my pr?

**Comment by lhein** [comment]
We will review it soon. Thank you for your patience.
