### ISSUE TITLE
2-way sync for URI field

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#296]
### Please describe the feature that you want to propose
Provide a class that takes a `syntax` string and a component parameters object and transforms it into the new `URI`. This conversion needs to be 2-way, meaning that providing a syntax and a URI string, should generate the object.

### Context
The `URI` field from a Camel component has a special meaning, as configuration might be represented using it.

As an example, the timer component has the following parameter, marked as `kind: path`:
```
"loggerName": { "kind": "path", "displayName": "Logger Name", ...  "description": "Name of the logging category to use" },
```
whereas the component itself has a syntax property, signaling where this parameter should go:
```
    "syntax": "log:loggerName",
```
_example taken from [here](https://github.com/apache/camel/blob/camel-3.20.x/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/log.json#L17):_

### Examples
Providing the syntax string `log:loggerName` and the URI string `log:myLog`, it should generate the following object:
```json
{
  "uri": "log:myLog"
  "loggerName": "myLog"
}
```

whereas providing the syntax string `log:loggerName` and the following object `{ "loggerName": "myLog" }`, it should generate the string `log:myLog`

### Prerequisite of https://github.com/KaotoIO/kaoto-next/issues/274

**Comment by lhein** [comment]
I think what we really need is a function that takes a URI as input and then moves all the path params and uri parameters into the parameters section. (see https://camel.apache.org/manual/faq/how-do-i-configure-endpoints.html)

@lordrip wdyt?

**Comment by lordrip** [comment]
Yes, this is what this issue aims for, going from the URI syntax (mind syntax and not query parameters) to an object. After this, we could aim to do the same for parameters.

This function can be leveraged where we see fit.

**Comment by lhein** [comment]
@kumaradityaraj can you share the status of your work?
