### ISSUE TITLE
Incorrect header in the configuration panel

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#302]
When selecting a node on the canvas then the right side configuration panel opens to let you configure the parameters. When selecting an endpoint on the canvas (a from or a to for routes) you will find a section in the panel called "Component Parameters" which is not named correctly. The parameters / properties you are editing here are "Endpoint Properties" and hence we should name it like this.

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/5d684b8a-b779-47ee-8fc1-282a35434022)

**Comment by corners2wall** [comment]
@lhein  I am afraid but I can't see `Component Properties` section on screenshot, maybe `Component Parameters` ? 
In this case rename `Component Parameters` to `Endpoint Properties`, right?

**Comment by lhein** [comment]
Yes, that would be my suggestion.

**Comment by corners2wall** [comment]
Fix in #305

**Comment by lhein** [comment]
Thank you very much for your contribution and congratulations to your first merged PR in the project, @corners2wall ;)
