### ISSUE TITLE
Remove duplicated headlines

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#304]
Users know what they selected in the menu and don't need to be reminded of their selection by mentioning it again in the screen that opens.

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/100a797c-015c-4515-bf7d-7c0e395a562d)

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/49788594-889d-4dd2-91eb-a838d41d0385)

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/5d17ad73-d5ee-4d27-97bb-302465cb5211)

**Comment by lhein** [comment]
@lordrip wdyt? I would suggest removing the headline in the screens as they kind of duplicate the selection on the menu.

**Comment by lordrip** [comment]
> @lordrip wdyt? I would suggest removing the headline in the screens as they kind of duplicate the selection on the menu.

Initially, the headline was meant to distinguish between the standalone component and the composed page that holds it, and since we're moving forward with VSCode, I also think this is not needed anymore, so we can spare it.
