### ISSUE TITLE
Kamelets in Camel Routes are not showing their icon

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#306]
### Please describe the feature that you want to propose

Currently, when designing a `Pipe` integration, we can see the Kamelets icons in the canvas nodes
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/aee7be77-0aa5-431c-b43a-ecd37d791297)

But when designing a `Camel Route`, we only see the default Camel icon
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/d94288d0-630e-4891-b69b-ee7e7e6a6bfc)

### Goal
Display the appropriate `kamelet` icon for each `kamelet` node

**Comment by lhein** [comment]
Yes, please :D
