### ISSUE TITLE
Error opening `Choice` step configuration

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#320]
### Describe the Bug

Also see: #311

`choice` is not yet configurable, possibly because the step parameter schema has `when` and `otherwise` as parameters, while it shouldn't (children have their own node)

### Steps to Reproduce the Bug or Issue

1. Add `choice` step
2. Click added `choice` step

### Screenshots or Videos

![Screenshot from 2023-11-10 07-23-15](https://github.com/KaotoIO/kaoto-next/assets/265462/e3de6acb-4539-4911-a4a6-492fe4f0900a)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
This happens because `Choice` has 2 properties that can't be understood by the UI schema, being `when` and `otherwise`. As these properties are handled by the canvas itself, we should filter them out from the configuration form.
