### ISSUE TITLE
Error opening `When` step configuration

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#321]
### Describe the Bug

Also see: #311, #320

`when` is not yet configurable, possibly because the step parameter schema has `outputs` as parameters. It seems `outputs` in the catalog parameters is about the children, so would need to be excluded when it's passed into uniforms for step configuration.

### Steps to Reproduce the Bug or Issue

1. Add `when` step
2. Click added `when` step

### Screenshots or Videos

![Screenshot from 2023-11-10 07-23-27](https://github.com/KaotoIO/kaoto-next/assets/265462/e526e88a-cf53-47d7-9f7d-bd1403ea2958)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by igarashitm** [comment]
This happens also with `filter` step, all branching step could hit the same issue.

**Comment by lordrip** [comment]
This happens because `When` has a property that can't be understood by the UI schema, which is `outputs`. As this property is handled by the canvas itself, we should filter it out from the configuration form.
