### ISSUE TITLE
Property panel for `onException` cannot load

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#331]
### Describe the Bug

![Image](https://github.com/KaotoIO/kaoto-next/assets/1105127/1aa5b9fa-94d2-4ae1-b98f-3f1bbf45b20e)

in console log:
```
Invariant Violation: Field not found in schema: "outputs.$"
    dB browser.js:38
    Dr JSONSchemaBridge.ts:13
    getField JSONSchemaBridge.ts:185
    getField JSONSchemaBridge.ts:174
    n Lodash
    getInitialValue JSONSchemaBridge.ts:245
    n Lodash
    getInitialValue JSONSchemaBridge.ts:254
    n Lodash
    qo useField.js:40
    n createAutoField.js:11
```

### Steps to Reproduce the Bug or Issue

1. create a route
2. add a model `onException` element
3. Select it
--> the property panel cannot load

### Platform

- OS: Linux
- Browser: Firefox
- Version: online kaoto-next

**Comment by igarashitm** [comment]
In YAML DSL schema, `onException` is not a part of `ProcessorDefinition`
https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json#L8-L194

So it's rather `onException` should not be allowed to be added as a step (#292).

`OnException` is an out-of-flow configuration like `beans` and `errorHandler` which could be a top level element in the YAML.
https://camel.apache.org/manual/exception-clause.html

**Comment by igarashitm** [comment]
While #292 should hide/disable non-step models in the catalog, keep this as an enhancement ticket to support `onException`.

**Comment by lordrip** [comment]
Although we shouldn't see `onException` as a node in the canvas, the issue regarding its configuration is due to the `outputs` property breaking the UI schema in a similar fashion as:
* https://github.com/KaotoIO/kaoto-next/issues/320
* https://github.com/KaotoIO/kaoto-next/issues/321
