### ISSUE TITLE
Route ID can't be edited in canvas

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#351]
### Describe the Bug

The route ID edition in the canvas is not stored.

### Steps to Reproduce the Bug or Issue

1. Create a route
2. in canvas - try to perform the route ID edit
3. see no changes

### Screenshots or Videos

![Peek 2023-11-16 10-01](https://github.com/KaotoIO/kaoto-next/assets/4180208/9afe27e4-7343-4d70-881f-a1f877d3e112)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lordrip** [comment]
Hi @tplevko, for this ticket, I think we would need to define a new method in the [`CamelResource` interface](https://github.com/KaotoIO/kaoto-next/blob/1d3ed91f26bbc32a7834d3cd502f4acd7963ab37/packages/ui/src/models/camel/camel-resource.ts#L18-L34), perhaps `setFlowId` or another name that you see fit better and then implementing it on each resource.

The method could look like the following:

```typescript
setFlowId(oldId: string, newId: string): void {
  // implementation goes here
}
```

After that, we can use said method in the [FlowList component, here](https://github.com/KaotoIO/kaoto-next/blob/1d3ed91f26bbc32a7834d3cd502f4acd7963ab37/packages/ui/src/components/Visualization/ContextToolbar/Flows/FlowsList.tsx#L59)
