### ISSUE TITLE
Export canvas to PNG

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#352]
### Please describe the feature that you want to propose

Related to feature parity  - in the old UI it was possible to export the canvas to PNG.
![Screenshot from 2023-11-16 10-18-45](https://github.com/KaotoIO/kaoto-next/assets/4180208/6309f3e5-b74b-488b-9b1e-ec3390312385)

**Comment by corners2wall** [comment]
@tplevko looks like a nice feature. Where is the button in the current UI? What is the default image name?
UPD: Assign to me please

**Comment by tplevko** [comment]
@corners2wall thanks for the interest in delivering this feature. 

There is currently no button for taking the png snapshot. Feel free to add one in the canvas toolbar next to the "copy to clipboard" button. The default image name is I think up to you, either use the route name, or something more generic.

Here is the old functionality implementation for reference:
https://github.com/KaotoIO/kaoto-ui/blob/1b9e5820491e6c3e8086ae092f3e214ccdaa661d/packages/kaoto-ui/src/components/ExportCanvasToPng.tsx#L19

**Comment by lhein** [comment]
Another example can be found here (from a project that uses topology too):
https://github.com/netobserv/network-observability-console-plugin/blob/main/web/src/utils/export.ts
