### ISSUE TITLE
Provide a story for the Canvas component

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#355]
### Please describe the feature that you want to propose

In order to ensure that we're not breaking existing functionality or visualization, it would be beneficial to have a story for the Canvas component that showcase a somewhat complex route, if possible, with 3 deep nested parts.

For instance, a few components, then a `choice` with 2 `when`s and 1 `otherwise`, and in the second `when` there's a few more nodes and then a `doTry` node with a couple `doCatch` and `finally`

**Comment by lhein** [comment]
@tplevko are u working on this atm?

**Comment by tplevko** [comment]
Hi @lhein, sorry for late response, yes - just created the PR - https://github.com/KaotoIO/kaoto-next/pull/396
