### ISSUE TITLE
Show a placeholder when there are no visible routes 

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#362]
### Please describe the feature that you want to propose

When there are no visible routes in the canvas, either because they don't exist or all are hidden, it would be convenient to show a placeholder to explain to the user why nothing is visible in the canvas

### No defined routes
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/91d82532-4883-41bb-81d6-a8d4650eb90f)

### No visible routes
![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/88b4e3cf-3b2a-45e1-a78a-0e4b0d2743a1)

### Notes
[Here's the implementation in kaoto v1](https://github.com/KaotoIO/kaoto-ui/blob/1b9e5820491e6c3e8086ae092f3e214ccdaa661d/packages/kaoto-ui/src/components/Visualization/VisualizationEmptyState.tsx)

**Comment by bilalshaikh292** [comment]
heyy is the issue still open ? I would like to contribute ?

**Comment by lordrip** [comment]
Hi @bilalshaikh292 😃 , did you have the chance to take a look into this?

**Comment by bilalshaikh292** [comment]
yes Sure I will Give this a try

**Comment by lordrip** [comment]
Thanks @bilalshaikh292 for your interest in this issue 💪 , since we're approaching an upcoming release, we need to have this implemented a bit sooner than expected, sorry for that.

In any case, you're always welcome to contribute to any issue that is interesting to you.

Implementing it here: https://github.com/KaotoIO/kaoto-next/pull/681

**Comment by lordrip** [comment]
Hi @bilalshaikh292, no worries at all, thanks once again for your interest :smile:
