### ISSUE TITLE
Expression Configuration is not prefilled correctly

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#371]
You can see in the screenshot that the source shows a `constant` expression with value `404` but the expression field in the config panel is not showing that value.

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/7aa38fae-e01f-4bd8-b1db-36c38df33c62)

Additionally in the example shown above the `setBody` in the same `when` clause also has an error.  While the source says its using `constant`  and an empty string, the config panel shows `Simple` instead.

![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/30b6d61f-5869-4016-b3bd-59ea145bf468)

**Comment by lhein** [comment]
The missing values seem to be caused by the use of numbers instead of strings. Once I enclose the value with double quotes, the value shows up fine in the config panel.

**Comment by igarashitm** [comment]
@lhein good catch, can you attach the source code?

**Comment by igarashitm** [comment]
YAML source - https://github.com/GuilhermeCamposo/demo_camel-ldap/blob/main/examples/camel-k-kaoto/camel-k/ldap-route.yaml

**Comment by lhein** [comment]
related to #332 ?

**Comment by igarashitm** [comment]
uniforms throws away the values if the type is not right (schema says it's string but the actual value is a number). At the time it comes to CustomAutoField, the value is already `undefined`. We might need to enforce it to be a string, possibly by customizing the JSONSchemaBridge
