### ISSUE TITLE
Catalog browser filter is case sensitive and only name evethough the user see title

### ISSUE THREAD

**Issue by mkralik3** [KaotoIO/kaoto-next#40]
### Describe the Bug

Catalog browser filter is case-sensitive and uses a `name` even though the user sees the `title`.
e.g. let's say I would like to filter this tile
![image](https://github.com/KaotoIO/kaoto-next/assets/16251792/a7ae7d50-65e5-4271-a1d3-e584d0262804)

it's name is `aws2-ec2` however UI shows `title` so filter like
`AWS`, `AWS Elastic`, `aws elastic` don't filter that tile.

### Steps to Reproduce the Bug or Issue

^

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Could be possible to include some of the requirements from https://github.com/KaotoIO/kaoto-next/issues/24?

**Comment by mkralik3** [comment]
@lordrip Sure, I didn't noticed that issue.

**Comment by mkralik3** [comment]
Only description missing. Now, it should be working as described in  https://github.com/KaotoIO/kaoto-next/issues/24
