### ISSUE TITLE
How to organize the parts of the Kaoto UI for the VS Code extension

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#402]
In the VS Code extension we will not have the left side nav bar that we have in the live environment. So the question will be how to organize the different parts of the UI then.

One idea would be to introduce top or bottom tabs for the different editors we have. That would be the visual designer, the beans editor and in future other editors like REST, Metadata, Errorhandlers etcs. I am wondering if we can find a way to combine beans, metadata, error handler into a single tab like "Configuration". 

We had something similar in the Eclipse Fuse Tooling...

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/4b349706-8b3e-4e15-8666-f30a372bf438)

**Comment by lordrip** [comment]
First iteration towards this: https://github.com/KaotoIO/kaoto-next/pull/509

**Comment by lhein** [comment]
After the first iteration 2 issues became evident.

- when editing a Pipe you lose all the tabs once you click the tab for "Metadata" and you have to reopen the editor to get them back
- when switching from Camel Route to Pipe editing and saving the initial route, the source file does not get updated to the latest state / still contains the Camel Route

**Comment by lordrip** [comment]
> when switching from Camel Route to Pipe editing and saving the initial route, the source file does not get updated to the latest state / still contains the Camel Route


This [PR](https://github.com/KaotoIO/kaoto-next/pull/549) fixes this issue.
