### ISSUE TITLE
This node cannot be configured yet "sticks" to other node configurations, even though these can be configured

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#416]
### Describe the Bug

When trying to add a node, which can't be yet configured - without closing the side panel, the message that the node can't be configured is displayed also for nodes, which can be configured.

### Steps to Reproduce the Bug or Issue

1. add e.g. google-sheets to a camel route
2. try to configure the node - open the side panel for the node
3. without closing the panel - open second node, which can be configured already
4. see the message "node cannot be configured yet'" displayed also for the second node

### Screenshots or Videos

[Peek 2023-11-24 09-53.webm](https://github.com/KaotoIO/kaoto-next/assets/4180208/31ec49e3-4926-4fa8-be68-906bf04ce470)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [latest]

**Comment by lhein** [comment]
Workaround is to close the config panel and reopen on another node.
