### ISSUE TITLE
Catalog contains 3 CoAP element with exact same name and description

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#453]
### Describe the Bug

there are 3 CoAP components in the catalog with exact same name and description

### Steps to Reproduce the Bug or Issue

1. Open Catalog

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/b7e421c6-0621-4bb0-84e1-8d72e4860786)

### Platform

main branch on online version

**Comment by apupier** [comment]
after inserting them we can notice that they have different id:
![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/6544c050-7fc9-48ab-8d49-16c6c20de3d4)

**Comment by lhein** [comment]
That should be reported in an upstream issue with a suggestion to give better names to each of them to better distinguish.

**Comment by lhein** [comment]
![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/3596d060-1628-403d-a599-8f06a7f0e992)

**Comment by apupier** [comment]
for reference issue upstream to improve the catalog: https://issues.apache.org/jira/browse/CAMEL-20167

**Comment by lhein** [comment]
Suggestion for our catalog improvement:

![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/1f302c49-4ef6-4f3a-9510-188cbeeff4dd)

I am seeing 2 variants possible.....either just the `name` or even the full `syntax`
