### ISSUE TITLE
Property panel is not working for saga EIP

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#456]
### Describe the Bug

Property panel is not working for saga EIP

### Steps to Reproduce the Bug or Issue

1. create route
2. add saga model
3. select sage node
--> the property panel has an error `Field not found in schema: "option.$"`

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/a87af89a-9ecb-4e3f-a8c9-a653ee89bd32)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lhein** [comment]
duplicates #448
