### ISSUE TITLE
Increment spinner in config by 1 instead of 0.01 for integer types properties

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#457]
### Please describe the feature that you want to propose

For some properties the increment is really by 1 (like for port of Avro component) but for Buffer size of Dataformat Crypto it is 0.01 even if it is an integer

https://github.com/apache/camel/blob/3e42a34d2f6dd7befe1edde0cf33024abb944430/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/dataformats/crypto.json#L24C112-L24C119

https://github.com/KaotoIO/kaoto-next/assets/1105127/c31a126d-1056-4779-8f6c-4ba709faf5d0

**Comment by lhein** [comment]
We decided to not use the number field any more as it is too limiting for our cases and would also prevent us from using property placeholders. That's why we use now string fields.
