### ISSUE TITLE
Move the canvas to the left when opening the Configuration Form

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#507]
### Please describe the feature that you want to propose

It would be nice to move the canvas to the left when opening the configuration form, so this way we can still see the selected node.

**Comment by lordrip** [comment]
These are the docs for [@patternfly/react-topology](https://www.patternfly.org/topology/sidebar).

The idea is whenever the user clicks on a node, the canvas gets moved about 200px to the left side so we continue to see what was selected.

**Comment by kumaradityaraj** [comment]
By inspecting the HTML, we can see that the whole node canvas comes under one div which is <g> </g>.  It has an attribute transform and we can use it to change the value of x axis in the transform. The example of this g div is as below :- 

g data-surface="true" transform="translate(1099.4072698070968, 0.7441016787665831) scale(0.7504091016174855)"></g

Whenever a user clicks on any node then we can change the value of that x by which the canvas will come into complete view.

**Comment by kumaradityaraj** [comment]
I am unable to find out how we will send this x value to controller.getGraph().setLayout().

**Comment by lordrip** [comment]
Hi @kumaradityaraj, keep in mind that a g tag is not a div, it's a SVG tag that groups items, so it behaves differently. [the Docs](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g)

My suggestion would be to check the controller's API and see if there's a method to move the canvas first.

There are methods [to zoom in and zoom out](https://github.com/KaotoIO/kaoto-next/blob/fb224f496884f5c1e6148b40c507f83d73c2d31e/packages/ui/src/components/Visualization/Canvas/Canvas.tsx#L101), so probably there are methods to move the canvas as well, so maybe you could start there

**Comment by lhein** [comment]
@kumaradityaraj are you still working on this or may I assign someone else?

**Comment by lhein** [comment]
Ok, I will unassign this then.

**Comment by kumaradityaraj** [comment]
@lhein  I am working on it.

**Comment by abkieling** [comment]
@kumaradityaraj test

**Comment by lhein** [comment]
Can you give us an update on your progress ?

**Comment by kumaradityaraj** [comment]
I am figuring out the parameter through which we can send the data to move the flowchart to the left side when we click on a node.
