### ISSUE TITLE
Use the index property for sorting component's properties

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#51]
### Context

Currently, the Camel Catalog provides an `index` property for sorting purposes.

```json
  "componentProperties": {
    "bridgeErrorHandler": { "index": 0, "kind": "property", "
```

### Goal
The goal for this issue is to leverage said property and sort the component's properties table

**Comment by lhein** [comment]
cc @apupier

**Comment by apupier** [comment]
discussed in private chat.
As a summary:
* need to take care about naming of the component properties/options, path and query parameter (and api properties).
* we do not know what for the index was introduced (in Camel 4.0) - to be investigated

**Comment by lhein** [comment]
I am lowering the priority as it is still unclear to me what that index value is actually saying.

**Comment by lhein** [comment]
The `index` property should be used for ordering the parameters in the config form. Order is ascending.

**Comment by lordrip** [comment]
Since the schema is generated for components, iterating over the properties dictionary, the output is sorted as well:

| Firefox | Chrome | Schema |
| --- | --- | --- |
| ![Image](https://github.com/KaotoIO/kaoto-next/assets/16512618/e66c9798-4da9-4c12-9670-2a1c30fcaf03) | ![Image](https://github.com/KaotoIO/kaoto-next/assets/16512618/92ea7c4d-6c22-498b-8f03-a99854312ecd) | ![Image](https://github.com/KaotoIO/kaoto-next/assets/16512618/1e6c1174-74b1-4954-883c-14a7261257f3) |

**Comment by lordrip** [comment]
We would need to do the same for EIPs as well
