### ISSUE TITLE
make enum values accept strings additionally

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#512]
when trying to create a Kamelet (and probably in any other case where we have enums in a drop down box) I would like to put in a property placeholder but the drop down prevents that. I have to later on switch to the source view and add it there.

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/61c40881-fde7-4d5a-8861-0cb32fc37cf5)

**Comment by igarashitm** [comment]
Same for boolean checkbox. Also see https://github.com/KaotoIO/kaoto-next/issues/494

Two options in my mind
1. Add a tiny button next to and say `Use placeholder`, once clicked it's turned into a text field
2. Always use editable dropdown for enum and boolean. Note that in this case boolean field is shown with text, `true` or `false`

I personally prefer No.1

**Comment by igarashitm** [comment]
Also take password field into account - https://github.com/KaotoIO/kaoto-next/issues/503

**Comment by lhein** [comment]
`is shown with text, true or false`
It could actually also be YES and NO. I think that option 2 is probably the more flexible approach.

**Comment by igarashitm** [comment]
One another thing is that once #494 is implemented, the `enum` field could get 2 set of dromdowns, 1 is for `enum` values and the other is for existing properties. Maybe switch by seeing if `{{` is typed or not?
