### ISSUE TITLE
Create LoadBalancerEditor component

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#520]
### Please describe the feature that you want to propose

Yet another dynamic form rendering next to languages and dataformats. The `loadBalance` eip has several choices for the load balancing strategy and each of them has a different set of parameters.
https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json#L2361-L2367

The catalogs for them are in `model` category.
https://github.com/apache/camel/blob/main/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/customLoadBalancer.json

**Comment by lordrip** [comment]
Let's check first what we had in the past, support-wise.

**Comment by igarashitm** [comment]
Found that there's load-balance step extension, so it was somehow supported already. Moving to the 2.0 TP milestone.
https://github.com/KaotoIO/step-extension-repository/tree/main/load-balance
