### ISSUE TITLE
Remove empty object

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#529]
### Describe the Bug

~~Is there an option in YAML library to avoid that?~~ requirement is now to remove the empty object, when we have following
```yaml
parameters: {}
```

It should be removed.
One problem with this is that, once we remove the `parameters` and then user add any parameter after that, the `parameters` is added at the bottom. We'd also need to investigate if it's possible to control the order.

### Steps to Reproduce the Bug or Issue

1. Have some empty object parameter

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
After today's discussion, we're going to:

1. Avoid removing default values by default and delegate that functionality to a dedicated button instead
2. Avoid removing the empty parameters object.

Anything else @igarashitm ?

**Comment by lordrip** [comment]
If there's nothing else, I think we can close this issue

**Comment by igarashitm** [comment]
Sounds good to me! that's all I remember

**Comment by lordrip** [comment]
Alrighty, closing it now.
