### ISSUE TITLE
Show the component properties rather than endpoint properties

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#53]
### Context
In the Camel component definition catalog, there are 3 types of elements:

1. Headers
2. Component properties
3. Endpoint properties

Currently, the component properties' table is showing the endpoint properties, rather than the component properties.

### Goal
Display the component's properties instead.

**Comment by mkralik3** [comment]
As part of PR, the other properties for camel components ( Headers, Apis, Properties ) will be added as well and alignment with the camel catalog web page in general.
