### ISSUE TITLE
Show tooltips for each step on the canvas

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#538]
Each node on the canvas should have a tool tip with more details. The content should be determined with the following logic:

1. if there is a description set for the step, display the description
2. if there is no description set, we fall back to display the most relevant information for that step which can differ from step to step. Check the matching matrix and the code snippet provided below.

Matrix:
![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/7eea6b4a-326b-43c5-9220-af15171d048b)

Code:
```
switch (label) {
      case 'bean':
        displayValue = 'ref';
        break;
      case 'convertBodyTo':
        displayValue = 'type';
        break;
      case 'enrich':
      case 'interceptSendToEndpoint':
      case 'pollEnrich':
        displayValue = 'uri';
        break;
      case 'log':
        displayValue = 'logName';
        break;
      case 'onException':
        displayValue = 'exception';
        break;
      case 'setHeader':
      case 'removeHeader':
        displayValue = 'headerName';
        break;
      case 'setProperty':
      case 'removeProperty':
        displayValue = 'propertyName';
        break;
      case 'rollback':
        displayValue = 'message';
        break;
      case 'when':
        displayValue = 'expression';
        break;
    }

    // default handling is to use the id
    if (displayValue === '') {
      displayValue = this.id;
    }
```

**Comment by lhein** [comment]
An alternative idea for the fallback variant could be to show the description from the Camel Catalog for the given step.

**Comment by shivamG640** [comment]
Hi @lordrip ,

I created a draft PR, https://github.com/KaotoIO/kaoto-next/pull/629/files. 
Wanted to cross-check if I added the tooltip component correctly at the right place.
Please ignore the tooltip content part for now!

**Comment by lordrip** [comment]
Hi @shivamG640 , yes, I think so. Also, I know that you mentioned to ignore the tooltip content for now, I just want to let you know there's a `label` property with the description or the name of the component, so you could leverage that for the tooltip content.

**Comment by shivamG640** [comment]
Hi @lordrip, Thanks for the feedback, the mentioned changes worked for me but I wanted to wrap the whole Customnode component which I couldn't do. I don't know why it is not possible!
Regarding the tooltip content, I did see the `label` property, but it is falling back to component name when the description is not added. we instead want to show the default description from the schema according to Lars's last comment on this issue. Please correct me if I am wrong on this. Also I need help with understanding "most relevant information for that step" whing Lars mentioned on his first comment here.

**Comment by lordrip** [comment]
@shivamG640 in a nutshell, the CustomNode component uses a SVG context, meaning that it has its own DSL, that's why wrapping the entire node in Tooltip doesn't work. The alternative is to use the foreignObject tag so we can include html elements.

About the description, I don't think we can show meaningful content based on the schema description. Please @lhein can confirm
