### ISSUE TITLE
Support Camel Route onException

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#561]
### Please describe the feature that you want to propose

Splitted from #492 

Support configuring `onException` element alone in  Camel Route. Note that `routeConfiguration` also has `onException` as a property.

Since `onException` has `steps` inside, it needs flow visualization. Also see:
 - #492
 - #563

**Comment by igarashitm** [comment]
Since `onException` has `steps` inside, it needs flow visualization.

**Comment by lordrip** [comment]
Closing it in favor if #492

**Comment by lordrip** [comment]
Error handler docs: https://camel.apache.org/manual/error-handler.html

**Comment by lordrip** [comment]
onException docs: https://camel.apache.org/manual/exception-clause.html
