### ISSUE TITLE
Connect missing schema link between Camel K CRD and Camel YAML DSL

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#6]
### Please describe the task that needs to be done

In the `@kaoto-next/camel-catalog`, ATM we holds the Camel K CRD schema and Camel YAML DSL separately, without any information about the disconnection.

For example, Kamelet `template` is described as `object` in Camel K
https://github.com/apache/camel-k/blob/main/config/crd/bases/camel.apache.org_kamelets.yaml#L505-L508

This implicitly jumps to `RouteTemplateDefinition` in Camel YAML DSL
https://github.com/apache/camel/blob/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json#L3432

In the best case we can leverage external schema reference and directly point to the definition in Camel YAML DSL schema from Camel K CRD schema.
https://json-schema.org/understanding-json-schema/structuring.html

But we have to carefully test if the external reference resolution works, especially with uniforms. Can we have a logical path to the separate file? just relative file path works? etc.

In the worst case, we might need to import the part of Camel YAML DSL schema into Camel K CRD schema.

**Comment by lordrip** [comment]
Closing it since we're using individual schemas already
