### ISSUE TITLE
increase the vertical spacing between the different parameter fields

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#618]
![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/985d372b-303a-442c-ae4c-f7392ad504a1)

In the image above you can see that the fields are really close to each other and its hard to visually separate where a field starts and ends. Could we somehow increase the vertical spacing between the fields of the different parameters or find other ways to make it more clear?

**Comment by lordrip** [comment]
Yes, we can. I made #637, which brings the same fix that we did for v1. A final fix needs to be done on `patternfly-uniforms` side.
