### ISSUE TITLE
Missing field label in config form

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#620]
In the picture below you can see that each field has a label to describe what you configure there....only exception is the first first where users have on first sight no visible hint on what they configure there.

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/5def1e0e-6e2e-4547-b836-196f9246bec6)

**Comment by tplevko** [comment]
We can close, as this seems to be already fixed in https://github.com/KaotoIO/kaoto-next/pull/723
