### ISSUE TITLE
Hide Rest menu navigation item

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#670]
### Please describe the task that needs to be done

Currently, the REST option is not developed, and clicking on it redirects the user to an error page.

### Goal
The goal for this issue is to hide that menu entry.

**Comment by d4n1b** [comment]
Hi 👋 - can I take this "good first issue"?

**Comment by lordrip** [comment]
Hi @d4n1b, sure thing, thanks for your help 💪

**Comment by d4n1b** [comment]
> Hi @d4n1b, sure thing, thanks for your help 💪

Thanks @lordrip. I've created this PR: https://github.com/KaotoIO/kaoto-next/pull/671. Let me know if there are changes required - this is my first contribution to open source 🫢

**Comment by lordrip** [comment]
> > Hi @d4n1b, sure thing, thanks for your help 💪
> 
> Thanks @lordrip. I've created this PR: #671. Let me know if there are changes required - this is my first contribution to open source 🫢

In case of doubt, we have many other issues open just in case you wanna try it again 😇

**Comment by apupier** [comment]
> > Hi @d4n1b, sure thing, thanks for your help 💪
> 
> Thanks @lordrip. I've created this PR: #671. Let me know if there are changes required - this is my first contribution to open source 🫢

Congratulations and welcome to the community :-)

**Comment by lhein** [comment]
Also congratulations from me! Well done and keep it going :) Open Source is fun.
