### ISSUE TITLE
Config validation doesn't recognize parameters in the URI

### ISSUE THREAD

**Issue by igarashitm** [KaotoIO/kaoto-next#674]
### Describe the Bug

For example `activemq` component has a required parameter `destinationName`, and it could be specified in URI path parameter
`activemq:myQueue`

However the config validation #126 warns about missing `destinationName` if it's specified as a part of URI.

![Screenshot from 2024-01-18 14-05-33](https://github.com/KaotoIO/kaoto-next/assets/265462/507b0739-22c5-434d-8e70-0d0aa63de8bb)
![Screenshot from 2024-01-18 14-01-58](https://github.com/KaotoIO/kaoto-next/assets/265462/935ce8ed-01b2-41a8-a0d8-3800a27b3d08)

We need to also take care of the parameters in the URI.

### Steps to Reproduce the Bug or Issue

1. Add activemq step
2. Fill destinationName as a part of the `uri`

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
This was handled here: https://github.com/KaotoIO/kaoto-next/pull/711
