### ISSUE TITLE
Warning: React does not recognize the `labelIcon` prop on a DOM element

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#685]
### Describe the Bug

Opening the Configuration Form, generates the following warning:
![console-error](https://github.com/KaotoIO/kaoto-next/assets/16512618/364626a6-2e4a-4334-bd06-db316540a053)

This happens due to the `CustomJSONSchemaBridge` class

### Steps to Reproduce the Bug or Issue

1. Open a node in the canvas
2. Open the DevTools console
3. Notice the warning in the console

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Related issue: https://github.com/apache/incubator-kie-tools/issues/2093
Related PR: https://github.com/apache/incubator-kie-tools/pull/2114/files

**Comment by lordrip** [comment]
Hi @d4n1b, does this seem interesting to you? :eyes:

**Comment by d4n1b** [comment]
Hey @lordrip - count on me! 🖖
