### ISSUE TITLE
Missing spacing between nested form fields

### ISSUE THREAD

**Issue by abkieling** [KaotoIO/kaoto-next#695]
### Describe the Bug

The spacing between nested form fields is missing. See screenshot.

### Steps to Reproduce the Bug or Issue

1. Click on a "from" node in the visual editor.
2. Compare the spacing of top-level form fields and nested fields. You should notice the missing spacing between the nested form fields.

### Screenshots or Videos

![from-configuration](https://github.com/KaotoIO/kaoto-next/assets/1910095/e8bdfcb8-66b2-4168-a858-7d0183843e64)

### Platform

- OS: Linux
- Browser: Chrome
- Version: 120.0.6099.224

**Comment by lordrip** [comment]
@shivamG640, you need to find the [NestField](https://github.com/KaotoIO/uniforms-patternfly/blob/main/src/NestField.tsx#L40) component in [KaotoIO/uniforms-patternfly](https://github.com/KaotoIO/uniforms-patternfly) and create a new CSS class and add the following styles to the `Card` component:

```css
.nestfield-spacing {
  display: grid;
  gap: var(--pf-v5-c-form--GridGap);
}
```

**Comment by lordrip** [comment]
After that, we need to migrate [this file](https://github.com/KaotoIO/kaoto-next/blob/93a19cf22877069e6f435ca8882d4f9bf9984964/packages/ui/src/components/Visualization/Canvas/CanvasForm.scss) into patternfly-uniforms as well, so we can have the stylings in one place.

**Comment by shivamG640** [comment]
@lordrip 
I went through the repo and might need your help in understanding a few things:
1. How can I test changes locally after making changes to the uniforms-patternfly repo. Do we do this by linking the 2 projects?
2. I tried the npm link process but unable to with the following error:
```
npm link @kaoto-next/uniforms-patternfly
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

```
3. While trying to link with yarn, I directly ran the command `yarn link ../../../uniforms-patternfly` on the UI workspace providing the relative path to the other repo. I am getting the following error:
`Cannot link @kaoto-next/uniforms-patternfly into @kaoto-next/ui$wsroot$@workspace:packages/ui dependency sass@npm:1.70.0 conflicts with parent dependency sass@npm:1.66.1`

**Comment by lordrip** [comment]
@shivamG640, the error message happens because we're using `yarn`, then we can't use `npm` for the repository operations.

In order to link both projects you need to do the following:

```
# Step 1: Build uniforms-patternfly
cd <uniforms-patternfly-cloned-folder>
yarn build

# Step 2: Use the locally built uniforms-patternfly
cd <kaoto-cloned-folder>
yarn link <uniforms-patternfly-folder>
```

Now, whenever you make a change in the library, you will need to rebuild it, you could do it by following the first step

**Comment by lordrip** [comment]
Here are [the related docs](https://yarnpkg.com/cli/link)
