### ISSUE TITLE
In VSCode extension - "doesn't support multiple routes" tooltip is not displayed

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#706]
### Describe the Bug

Tooltip with information about the editor not being able to create multiple routes of certain type is not displayed in the VScode extension.

Beyond the scope of this issue (idea for discussion, can open separate issue) - could the "New" button be hidden in case the resource type doesn't support multiple routes?

### Steps to Reproduce the Bug or Issue

1. in VSCode extension - create a Pipe/Kamelet resource
2. try to create multiple resources using the "New" button

### Screenshots or Videos

Web app situation:

https://github.com/KaotoIO/kaoto-next/assets/4180208/ad33235f-1c61-4b25-b780-156ecf93f7d0

VSCode situation:

https://github.com/KaotoIO/kaoto-next/assets/4180208/3609a287-dcbc-4bed-ba84-5415431932ce

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
After checking, the only potential difference between VSCode and the web version is the mismatch between React 17/18. Still needs more investigation to determine if that's the case.

**Comment by lordrip** [comment]
This looks related to: https://github.com/KaotoIO/kaoto-next/issues/431

**Comment by lordrip** [comment]
Back to `Todo` as it's not a blocker for the `TP1` release

**Comment by lordrip** [comment]
I can't reproduce it locally or in vscode.dev 🤔 

### Local build
![Image](https://github.com/KaotoIO/kaoto-next/assets/16512618/2d72a7d9-9d3d-4dbd-9ef7-48a01e4f22a1)

### VSCode.dev
![Image](https://github.com/KaotoIO/kaoto-next/assets/16512618/ea038cab-54d2-4898-a787-747d50354d50)

**Comment by lordrip** [comment]
No longer reproducible with VSCode@1.86.0
