### ISSUE TITLE
Data Format config field needs improvements

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#718]
- the title label is bigger than all other labels in the form
- there is a different vertical spacing between the drop down and the follow up fields then between all the other fields
- the title label `DataFormat` should be renamed `Data Format`
- when selecting or changing the library for a data format, the dependencies section in the source needs to be updated, otherwise the integration will fail with missing dependency (kamelet)

![Image](https://github.com/KaotoIO/kaoto-next/assets/435853/657b17cc-bedc-40be-87a3-ebcd450066ae)

**Comment by lhein** [comment]
progressing to backlog

**Comment by tplevko** [comment]
Closing, as the last point in this issue is tracked in https://github.com/KaotoIO/kaoto-next/issues/489#issuecomment-1840948820 and the remaining tasks are already implemented.
