### ISSUE TITLE
Keep Form and Node Validation status in sync

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#719]
### Please describe the task that needs to be done

Once the `CanvasForm` validation starts, keeping it in sync with the `Canvas` node is needed.

**Comment by lhein** [comment]
I see a merged PR in the history. Is that fixing this issue, @lordrip ?

**Comment by lordrip** [comment]
No, not yet, this is a pending topic we need to keep in mind when implementing the next step of the validation process

**Comment by lordrip** [comment]
Just a consideration for the implementation of the Form validation.
