### ISSUE TITLE
Fields in config panel for Pipes are very spaces

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#732]
### Describe the Bug

there si a lot motre space in config panel for Pipes

### Steps to Reproduce the Bug or Issue

1. create a pipe
2. select the log-sink

### Screenshots or Videos

![image](https://github.com/KaotoIO/kaoto-next/assets/1105127/20d23df2-d41c-4c73-b67b-85371c21d29c)

### Platform

Kaoto online

**Comment by lordrip** [comment]
@apupier this is the "desired" behavior, as you can see the wrong one is [reported here](https://github.com/KaotoIO/kaoto-next/issues/695)

**Comment by lordrip** [comment]
The explanation about why this happens is because for `Pipes`, there's no nested schema, as opposed to Camel Routes, in which the nested schema gets rendered very close to each other, as it's missing some styling.

**Comment by apupier** [comment]
:-( why desired? it implies a lot more scrolling

**Comment by lordrip** [comment]
Otherwise it looks a bit confusing as it's very close to each other, but nevertheless, that doesn't mean that we're not gonna address the scrolling issue of course, that will happen regardless :smile:

**Comment by lhein** [comment]
Can we close this issue?

**Comment by lordrip** [comment]
I think yes, since we have:

- https://github.com/KaotoIO/kaoto-next/issues/695
- https://github.com/KaotoIO/kaoto-next/issues/754

The scrolling issue will be handled in:
- https://github.com/KaotoIO/kaoto-next/issues/278

I'll let the final decision to @apupier 😃
