### ISSUE TITLE
when filtering the catalog we should give users hints on results in all tabs

### ISSUE THREAD

**Issue by lhein** [KaotoIO/kaoto-next#745]
As an example....if I am on the components tab and filter for "setHeader", then I will have no results in the components tab but 2 results in the processors tab. However we do not tell users about those results and this makes it hard for new users. I would suggest to add a "(<n>)" behind the tab labels when filtering for something. This also includes filtering via labels and a combination of labels and text.

**Comment by d4n1b** [comment]
Hey everyone,
Aligned with @tplevko's suggestions & conversations I had with @lordrip, would something like this work cover your use case? - if so, more than happy to create a PR as soon as I have this done.

<img width="1120" alt="image" src="https://github.com/KaotoIO/kaoto-next/assets/17992718/8fb6af66-ddf3-44a9-b308-fae42393fcd9">

**Comment by lordrip** [comment]
> I am not sure I understand how this relates. What is the "0" standing for?

0 means "No filter selected"

**Comment by d4n1b** [comment]
Apologies. I forgot to link the [issue](https://github.com/KaotoIO/kaoto-next/issues/686) @tplevko created so I've updated my comment.

I was under the impression both issues could be merged as they look related. Not only adding the numbers, but also allowing to extend the filters enabling others like `stable`/`preview` or `versions` - happy to only add the numbers next to the type, if that's the only functionality desired.

**Comment by lhein** [comment]
Ah, thanks for the clarification :) Do you intend to keep the 3 type buttons? Am asking because I can't see them in your pic.

![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/55bf3be4-4ba0-4619-9197-1f8b05888095)

**Comment by d4n1b** [comment]
Hey @lhein, in the draft design I made you can see the types in form of checkboxes (1), as my understanding is that it can be filter by all/one/many. I also included the existing tags filters (2)

![Pasted_Image_27_01_2024__19_50](https://github.com/KaotoIO/kaoto-next/assets/17992718/f821c3d7-7fa1-41a0-bc48-e4745a7230f0)

**Comment by lordrip** [comment]
![Image](https://github.com/KaotoIO/kaoto-next/assets/16512618/8e3134bc-f216-4dd3-b3cd-ea90e31395fd)
