### ISSUE TITLE
Provide a release container image

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#746]
### Please describe the task that needs to be done

Currently, our release workflow [is described here](https://github.com/KaotoIO/kaoto-next/blob/5a2e90a07cbe58997a3ce7a79f53a9829848149c/RELEASE.md), but as a summary:
1. Create a PR updating the version
2. Create a Tag
3. A new npm package gets deployed

If possible, it would be nice to continue that workflow and deploy a container image using that very same tag.

This is the workflow file: [Publish npm package](https://github.com/KaotoIO/kaoto-next/blob/5a2e90a07cbe58997a3ce7a79f53a9829848149c/.github/workflows/publish-npm-package.yml)

**Comment by lburgazzoli** [comment]
@oscerd

**Comment by oscerd** [comment]
I'll try to read an we can come up with some idea on how to automate the full workflow

**Comment by oscerd** [comment]
If something is wrong, I worked on this just 20 mins, so please report.

**Comment by oscerd** [comment]
The action makes it automated, it will check the last one and create the next minor by default, but there are a bunch of options to use
https://github.com/anothrNick/github-tag-action

**Comment by oscerd** [comment]
So we need to understand how we want to go, this approach will only work when a PR is merged and the label is 'release-pr'.

**Comment by lordrip** [comment]
The `npm` deployment is made by an npm package called `lerna-lite` and what it does is check what's the version from the `package.json` file and see whether this version exists in the registry or not. In case it doesn't exist, then `lerna-lite` publishes it.

**Comment by lordrip** [comment]
> So we need to understand how we want to go, this approach will only work when a PR is merged and the label is 'release-pr'.

I'm good with either approach, my preference would be towards providing the tag version the least as possible :smile: .

So, let's say that we want to publish the `2.0.0-TP2`version.

For that, I'll change (manually, currently) all `package.json` versions and submit a PR, if we could read this information and create the TAG with it after the merge, it would be awesome.

If that can't be made at the moment, then I think it would be preferable to trigger the release in the same fashion that we're doing now which is creating the tag and release by hand in the GitHub UI.

For the former, we can agree on having the PR title in a fixed way or maybe the commit message in a particular way, whatever is easier to read.

**Comment by oscerd** [comment]
Another possibility is avoiding trigger this at PR merged, but simply define a workflow_dispatch where you're going to pass the tag version you want to define, this will trigger the tag creations eventually. Is it better in that case?

**Comment by oscerd** [comment]
Like this: https://github.com/oscerd/kaoto-next/blob/main/.github/workflows/create-tag.yaml

**Comment by lhein** [comment]
@oscerd Andrea, is that issue complete now?

**Comment by oscerd** [comment]
Not yet, the image step is missing at this stage
