### ISSUE TITLE
Improve component's icon visualization

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#76]
### Context
Currently, the components in the Canvas view are represented by a circle, without any icon.

### Goal
The goal for this issue is to provide:
1. A default icon for all components.
2. Custom icons for EIPs
3. An easy place for these icons to be overridden, meaning that if at a later stage, we want to add a different icon for another component, it should be a matter of adding a new asset and linking it through a list.

### Note
Please see [`IconResolver`](https://github.com/KaotoIO/kaoto-next/blob/96b21e48d1b483ce0dae46d6b28a53c02d1ebdad/packages/ui/src/components/IconResolver/IconResolver.tsx)

**Comment by lhein** [comment]
Also if we have a kamelet endpoint in a Camel Route we should use the right icon for the specific kamelet referenced after `kamelet:`.

**Comment by igarashitm** [comment]
As a part of #149 I'm seeing where kamelet definition and `VisualizationNode` meets, the easiest from my side is to just copy the icon data into `VisualzationNode`.

Looking at the following demo, it needs to create a `CustomNode` equivalent and put the `Icon` inside, then pass it from the `customComponentFactory`, which is eventually registered to the `Visualization` controller.
https://www.patternfly.org/topology/custom-nodes

**Comment by lordrip** [comment]
Adding EIPs icons to the project: https://github.com/KaotoIO/kaoto-next/pull/259

**Comment by lordrip** [comment]
Base functionality implemented already, and EIP icons have already been provided.
