### ISSUE TITLE
Provide a Kamelet configuration panel

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#782]
### Please describe the feature that you want to propose

The goal for this issue is to provide a tailored Kamelet configuration panel that covers the most common aspects of it.

This is a broader issue that encompasses many steps.

### Steps
- [x] Create a JSON Schema with the appropriate fields. These fields should cover: #793 
    1. metadata.name: string
    1. metadata.annotations.common fields
      2. 'camel.apache.org/kamelet.support.level': string;
      2. 'camel.apache.org/catalog.version': string;
      2. 'camel.apache.org/kamelet.icon': string;
      2. 'camel.apache.org/provider': string;
      2. 'camel.apache.org/kamelet.group': string;
      2. 'camel.apache.org/kamelet.namespace': string;
    1. metadata.annotations.* object<string, string>
    1. camel.apache.org/kamelet.type: "source" | enum | `source`, `action` or `sink`
    1. metadata.labels: object<string, string>
    1. spec.definition.title: string
    1. spec.definition.description: string

- [x] Provide the JSON Schema in the Entities Catalog to be later on used by the form. https://github.com/KaotoIO/kaoto-next/pull/857
- [x] Loads the Kamelet Form with the Kamelet Schema. https://github.com/KaotoIO/kaoto-next/pull/864
- [ ] Read the Kamelet metadata object and transform it into the Custom Form (SourceCode -> CustomForm)
- [ ] Transform the custom object into the right Kamelet metadata object and store it (CustomForm -> SourceCode)

We need this issue to be implemented first: https://github.com/KaotoIO/kaoto-next/issues/878

**Comment by lordrip** [comment]
@shivamG640 this is the issue that I talked to you about, I haven't finished defining the other steps, but at least we show the first one.

**Comment by lordrip** [comment]
You could use: https://rjsf-team.github.io/react-jsonschema-form/ for testing your JSON Schema

**Comment by lordrip** [comment]
You could also check the Camel YAML DSL JSONSchema: https://raw.githubusercontent.com/apache/camel/main/dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json

**Comment by lordrip** [comment]
In order to display a raw metadata field, you need to use:
```json
    "metadata" : {
      "type" : "object"
    },
```

**Comment by lordrip** [comment]
You could place your schema alongside this file: https://github.com/KaotoIO/kaoto-next/blob/f85418930c0d59c3da9d3603fa9c094ffa51d82f/packages/camel-catalog/assembly/src/main/resources/schemas/PipeErrorHandler.json

**Comment by shivamG640** [comment]
![image](https://github.com/KaotoIO/kaoto-next/assets/73224329/3c6cdc54-e2dd-445a-88b8-c7782eef34e7)
![image](https://github.com/KaotoIO/kaoto-next/assets/73224329/e3805f17-1dc6-4b41-bf3e-d5ea1f0c2f3a)
![image](https://github.com/KaotoIO/kaoto-next/assets/73224329/fc2deea4-e13e-493e-8325-0392056c3eb3)
@lordrip This is how the Kamelet configuration looks like using the designed schema!

**Comment by lordrip** [comment]
Awesome, what do you think about having both labels and annotations at the end of the form instead?

I think we're in a good spot for a PR now 😃

**Comment by lordrip** [comment]
Once the form is provided, we need to override the `updateModel` method in the `kamelet-visual-entity.ts` file to check for the root path

```typescript
  updateModel(path: string | undefined, value: unknown): void {
// check whether we're trying to update the root or not, there's a variable called `ROOT_PATH`
// if that's the case, map the object to the kamelet metadata object and then save it
    if (!path) return;

    setValue(this.route, path, value);
  }
```

**Comment by lordrip** [comment]
We're missing the `properties` property from the Kamelet schema, here's [the related issue](https://github.com/KaotoIO/kaoto-next/issues/880) to tackle it
