### ISSUE TITLE
MongoDB and ActiveMq icon too large in the canvas diagram

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#788]
### Please describe the feature that you want to propose

The ActiveMQ connector icon is too large in the canvas diagram:
![Screenshot from 2024-02-05 09-20-14](https://github.com/KaotoIO/kaoto-next/assets/4180208/5def72fa-c56d-4863-af73-ec902c9462d2)

This is even more visible with the mongoDB:
![Screenshot from 2024-02-05 09-24-20](https://github.com/KaotoIO/kaoto-next/assets/4180208/3392001a-8d53-4e93-b21f-58de43d90978)

**Comment by lhein** [comment]
I think the mongoDB icon is coming from the Kamelet here. Both icons are however SVGs.

**Comment by oscerd** [comment]
If you have better svg, I can change them in the catalog. No problem.

**Comment by lhein** [comment]
hmm....I don't think the SVG is the issue here as the image is displayed fine in other locations like the catalog or the config form. I sense some problem in how topology view renders it.

**Comment by lhein** [comment]
![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/f6174c4e-8117-40d6-9876-1f03e649d238)

**Comment by lhein** [comment]
There is a way to style the used topology step icon...scaling the width and height down to 40% would look like this....
![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/91013723-36be-41dc-9f5c-0f8aeddcbf8d)

**Comment by lordrip** [comment]
the `log` icon seems a bit smaller now, maybe there's an intermediate way to limit the maximum height of the image

**Comment by lhein** [comment]
yeah, still checking

**Comment by lhein** [comment]
```
style={{maxHeight: '80%', width: 'auto'}}
```
![grafik](https://github.com/KaotoIO/kaoto-next/assets/435853/a93257b9-8956-4e35-8fab-4d7c559c3fb4)
