### ISSUE TITLE
Cleanup unit test execution logs

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#801]
### Please describe the task that needs to be done

Currently, there's much noise when executing unit tests, partially due to a misconfiguration in the `uniforms-patternfly` library, making it hard to debug them.

**Comment by tplevko** [comment]
@lordrip can we close this and revisit if further clean up is needed?

**Comment by lordrip** [comment]
Sure @tplevko, closing it, thanks for the help :muscle:
