### ISSUE TITLE
Unknown node - add help for the user 

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#803]
### Please describe the feature that you want to propose

Based on feedback from @GuilhermeCamposo :

... We should explain what is the question mark node and that the user needs to fix it or work on the yaml file.

![screenshot_2024-01-29_131642](https://github.com/KaotoIO/kaoto-next/assets/4180208/353dce21-46b3-4945-89dc-ff4092cc04a1)

**Comment by lordrip** [comment]
From Jenn:

> If you use an inline alert, one option that might work well is the expandable alert: https://www.patternfly.org/components/alert#expandable-alerts
This lets you have a brief title that describes the situation, and hide the additional details that explain the situation.

For example:
Node is not a known type
Configuration properties are not available when the node is not a known type.

![image](https://github.com/KaotoIO/kaoto-next/assets/16512618/ac7dedd9-c409-435e-960d-b7d4142ef6ee)
