### ISSUE TITLE
`codeEditor/sourceCodeActions.cy.ts` seems flaky

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#831]
### Describe the Bug

From time to time, the `sourceCodeActions` test fails

### Steps to Reproduce the Bug or Issue

```
  │ ✖  codeEditor/sourceCodeActions.cy.ts       00:39        7        6        1        -        - │
```

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [2.0.0-TP2-dev]

**Comment by lordrip** [comment]
Waiting to have a stacktrace

**Comment by tplevko** [comment]
failure observed here - https://github.com/KaotoIO/kaoto-next/actions/runs/8249394234/job/22561871654?pr=896

```
       User Add a new branch in the YAML:
     AssertionError: Timed out retrying after 8000ms: Expected to find element: `[data-type="node"][data-id^="atlasmap"]`, but never found it.
      at  (webpack://@kaoto-next/ui-tests/./cypress/e2e/codeEditor/sourceCodeActions.cy.ts:64:0)
      at __webpack_modules__</setRunnable/runnable.fn (http://localhost:4173/__cypress/runner/cypress_runner.js:138718:43)
```

![Test source code editor -- User Add a new branch in the YAML (failed)](https://github.com/KaotoIO/kaoto-next/assets/4180208/072349e6-b0ee-4331-905c-711f6b6eaa50)
