### ISSUE TITLE
Camel 4.5 - CamelK Pipe with dataTypes can now use camel-catalog to show list of known values

### ISSUE THREAD

**Issue by davsclaus** [KaotoIO/kaoto-next#836]
### Please describe the feature that you want to propose

in the camel-catalog we know have a list of known transformer from Camel 4.5 onwards.
https://github.com/apache/camel/tree/main/catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/transformers

In the YAML for camel-k pipe then you can use those in datatype in|out,
https://github.com/apache/camel-kamelets-examples/blob/main/jbang/knative/pipes/timer-source-pipe.yaml#L44

Its the format field where you can select the name of the transformer.

More in this blog
https://camel.apache.org/blog/2023/12/camel-data-types/

Christoph known more about this

**Comment by lordrip** [comment]
Got it, thanks for reporting it @davsclaus 👍

**Comment by lordrip** [comment]
We could enable a TextField as a first step
