### ISSUE TITLE
Overlapping controls in side panel in canvas

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#847]
### Describe the Bug

This is an issue with the controls e.g. in Saga processor in the side panel canvas configuration - the side scrolling bar in the panel is overlapping with the add and remove buttons for options.

### Steps to Reproduce the Bug or Issue

1. Create Saga processor to integration
2. Try to add and remove "options" using the side controls

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/4180208/0e374ba5-afae-471d-ab27-2dcc0f858a48

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
It seems like the form is being collapsed, instead of the container. Ideally, the form should grow as necessary, while the sidebar container should be static at 100% with `overflow: scroll`
