### ISSUE TITLE
Parsing an OpenApi file should display error messages if happens

### ISSUE THREAD

**Issue by lordrip** [KaotoIO/kaoto-next#85]
### Context
When failing to parse an OpenApi file, if there's an error message, the UI should show this error message to the user.

![Screenshot from 2023-09-05 10-22-56](https://github.com/KaotoIO/kaoto-next/assets/16512618/d4049b92-fbcf-4cba-9262-65ab3e3513c8)

**Comment by lhein** [comment]
Do we have such a functionality already?

**Comment by lordrip** [comment]
This will be implemented using JBang
