### ISSUE TITLE
Route container config - logMask switching to false for the first time not persisted

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#861]
### Describe the Bug

There is an issue when configuring the route container using the side panel - the logMask checkbox property, which has default value set to `true` is not persisted when switched to false for the first time. This results in the default value to be reset when switched back to the canvas. See video.

### Steps to Reproduce the Bug or Issue

1. open the route configuration sidebar
2. switch the "logMask" property to false
3. swith to code editor view - see the logMask wasn't configured
4. switch back to canvas view - see the "logMask" is still set to true in the configuration sidebar

### Screenshots or Videos

https://github.com/KaotoIO/kaoto-next/assets/4180208/a2983ea4-b5e7-4660-bf77-842a541e644a

### Note
Once this is fixed, we can reenable: https://github.com/KaotoIO/kaoto-next/blob/a13cb4c3dbaca25e2a4f7a5abce695df3d84edb5/packages/ui-tests/cypress/e2e/designer/rootContainersConf.cy.ts#L82

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 0.30.0]

**Comment by lordrip** [comment]
Oh, if I try the same, using the `daemon` property of the `timer` component, it behaves as expected, so maybe it's related to the root container only.
