### ISSUE TITLE
Log level config dropdown

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#865]
### Please describe the feature that you want to propose

The log levels configuration could be provided as a dropdown with preconfigured list with values:
e.g. here (Retries Exhausted Log Level, Retry Attempted Log Level):

![Screenshot from 2024-02-22 15-24-12](https://github.com/KaotoIO/kaoto-next/assets/4180208/05c7dea8-bbf0-4557-a636-854ed2482c8a)

**Comment by lordrip** [comment]
This will be handled here: https://github.com/apache/camel/pull/13312

**Comment by lhein** [comment]
blocked until we have a new camel version with the fix available

**Comment by lhein** [comment]
I see it already working for the log eip and component. Can we resolve this then?

**Comment by lordrip** [comment]
Will be released with Camel 4.5, closing the issue now
