### ISSUE TITLE
Node ID in node actions dropdown - change to node name, or description

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#872]
### Please describe the feature that you want to propose

The Node ID is confusing in the node actions dropdown. 
The dropdown should either use the node name to reference the node, or the description provided by the user:

![Screenshot from 2024-02-26 13-20-50](https://github.com/KaotoIO/kaoto-next/assets/4180208/74b0a697-5a59-410c-bcf8-f245fb826778)

**Comment by lordrip** [comment]
Let's remove the internal node-id instead, so it could read as:

1. Add node before (Prepend) / Insert before
2. Add node after (Append) / Insert after
3. Replace
4. Remove

In the case of a child node, we could name it as "Insert child" / "Add a child"
![Image](https://github.com/KaotoIO/kaoto-next/assets/16512618/2f495d99-7b81-4d71-b871-9fbf3daf06a1)
