### ISSUE TITLE
Storybook - add rules to limit the storybook action triggering

### ISSUE THREAD

**Issue by tplevko** [KaotoIO/kaoto-next#883]
### Please describe the task that needs to be done

Add rules to restrict the storybook triggering - e.g. limit the directories where the code changes happened - similar to [this config](https://github.com/atlasmap/atlasmap/blob/main/.github/workflows/supported-build.yml#L64-L67)

**Comment by lordrip** [comment]
@tplevko , what do you think about skipping the storybook action when the PR is not ready? This way we can push all the changes as many times as we want for review purposes, and once we're good, we can enable the PR for an entire test suite

**Comment by lordrip** [comment]
Also, using `[skip ci]` seems to avoid executing the workflow, so maybe that could be an alternative from the contributor side to avoid extra runs


```
feat(CanvasForm): Add support for ErrorHandler [skip ci]
```
