### ISSUE TITLE
Blinking selection on hover of step name

### ISSUE THREAD

**Issue by apupier** [KaotoIO/kaoto-next#907]
### Describe the Bug

Blinking selection on hover of step name after first selection of the node

### Steps to Reproduce the Bug or Issue

1. create a route
2. select the node
3. place mouse hover name of node
--> it is blinking
I cannot reproduce if I move somewhere elese and then go back. I need to unselect the node, then reselect and re-hover to reproduce

### Screenshots or Videos

![blinkingSelectionOnHover](https://github.com/KaotoIO/kaoto-next/assets/1105127/28fe28dd-4823-4847-bf75-eb992271efa1)

### Platform

online version with Chrome

**Comment by lordrip** [comment]
Pending to check how to reproduce (check different browser)

**Comment by apupier** [comment]
Tried different browsers and different examples, i'm unable to reproduce anymore
