### ISSUE TITLE
Support for AtlasMap

### ISSUE THREAD

**Issue by yuvanmytri** [KaotoIO/kaoto-next#961]
### Please describe the feature that you want to propose

Seems like AtlasMap is not yet supported on Kaoto UI,
Is there any roadmap to support this?
https://camel.apache.org/components/3.22.x/atlasmap-component.html

**Comment by lhein** [comment]
When looking at the Camel catalog for Camel 4 I can no longer spot AtlasMap as supported component.

**Comment by lhein** [comment]
However we are working on a new visual data mapper as part of the Kaoto project. This effort is still very early and will probably take longer until we can offer something.

**Comment by yuvanmytri** [comment]
> However we are working on a new visual data mapper as part of the Kaoto project. This effort is still very early and will probably take longer until we can offer something.

That's a great news.
