### ISSUE TITLE
Quotes missing on parameter values

### ISSUE THREAD

**Issue by joshdreagan** [KaotoIO/kaoto-next#971]
### Describe the Bug

Noticed that Kaoto doesn't always quote values when it might need to. For instance, for the REST Component, there's a `bindingMode` parameter. It's an enum and one of the possible values is "off". So Kaoto generates `bindingMode: off` instead of `bindingMode: "off"`. Which causes the YAML to interpret the value as "false" instead of the literal "off".

### Steps to Reproduce the Bug or Issue

1. Create a new route
2. Add a rest producer
3. Set the bindingMode parameter to "off"
4. Inspect the YAML

### Platform

- OS: all
- Browser: all
- Version: 0.14.0

**Comment by igarashitm** [comment]
Note: In YAML 1.1, `off` is translated to boolean `false`
https://yaml.org/type/bool.html

YAML 1.2 doesn't do that
https://yaml.org/spec/1.2.2/#10212-boolean

We would need to quote the `off` anyway...
